version: '3.8'
services:
  chatterbox-tts:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - "./voices:/app/voices:ro"
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped